### ISSUE TITLE
Task #2 (Mockups)

### ISSUE THREAD

**Issue by ghost** [nikitadziadovich/Exadel#2]
0) be carefull with charset please, all cyrillic symbols are harmed (or better write all in english, no cyrillic - no problem ;) )

[-] [Minor] no invalid password state

[=] [score isn't decreased, just fyi] 
From UX point of view "Add screen" is not good, can't tell exactly what's wrong just a feeling. Mb it will be better to have both areas (for image and meta) with equal, bounded width and both centered in the screen. I mean have spaces from the screen corners and have a two blocks of content in the middle of the screen. (You can clarify exactly, what I mean on the practice., anyway no mark reduce here as it's totally subjective). 
[=] [Just FYI] the pattern for point 2 on "Add screen" called PopOver / PopUp, or exactly Autocomplete PopOver.

[-][9-10] tag field (group) should be described carefully (buttons behaviour missed ), Point 3 on "Add screen" isn't saying much as taginput is unknown pattern forour our mockups, it needs to be decribed.
[-] [Minor] Point 3 on "main logged" screen is ok, but it isn't describe behaviour ("browser date input field" - would explain btw, as it's "out of the box" pattern and field)
[-] [Minor] "Show more" behaviour wasn't explain

[+] wireframes almost ok, all that I wrote above is minor issues
Current mark 8
PS: don't worry much about works checking, we didn't forget you, we just need time. Feel free to ask after lecture or on pracice if you want review asap.

**Comment by nikitadziadovich** [comment]
ok, gotcha, thank you for checking!
should I correct the mistakes? or just mind it in the upcoming work?

**Comment by ghost** [comment]
You could correct works anytime (within reasonable limits, if much updates required) to increase your mark.
That one you can update anytime, just let me know to review it one more time.

**Comment by nikitadziadovich** [comment]
i've just updated mockups

**Comment by ala-n** [comment]
Ok, thanks!  
Looks fine for me now.
Current mark increased to 10.
