### ISSUE TITLE
Task #3 (HTML, CSS)

### ISSUE THREAD

**Issue by ala-n** [nikitadziadovich/Exadel#3]
HTML
[-] (minor) html lang attribute missed
[-] get rid of align attribute, such things should be in CSS
[-] (clean code) class name "in-header" doesn't say much. Basically it says where, but it doesn't say what. 
[-] do not use `<b>` just to make text bolder, you have CSS font-weight for that. `<b>` is for preformatted text.
[-] Try to use meaningful classes names and semantics, use flex in CSS it can solve much.
[-] (semantic cosmetic ) replace <div class="filter"  to <aside class="filter"
[-] (again semantic) `<h2 align="center">ФИЛЬТР</h2>` and all others hN
h2 is not "tag for big enough text" at all it is secondary level header text. 
[-] consider `<form>` tag for filter area inside to control all the fields in future.
[-] group filter areas using divs
[-] tag list is a list, so instead of div.tags > div.tag use ul.tags > li.tag and style it by CSS as you wish.
[=] container that contains only photo-post items (without buttons show more and all else) will save your time in the future.

CSS
[-] Do not override tags styles for hN, button, a, etc. globally, just to make button X bigger for example. 
Only one case acceptable for this: global style-guide.
[-] `margin-left: 2,5%;` is invalid property, number values use dot as a delimiter in CSS
[-] Try to not use floats for layout, use flex and grid instead.
[-] U need not vendor prefixes like here:
```
-webkit-align-items: flex-start;
	-webkit-justify-content: space-around;
```
just
```
	align-items: flex-start;
	justify-content: space-around;	
```
will be enough.
	
[-] try to group things in CSS
Just as abstract example:
```
header {...}
header .logo {...}
header nav.header-menu {}
.header-menu .menu-item {}
```

Current mark is 5 (to much mistakes for now)

**Comment by nikitadziadovich** [comment]
i've just updates html and css
sorry for late sending - was busy BSUIR CUP
i'm not really sure if i groupped css classes in a correct way, because i don't know how to group it without copying some properties - i only sorted classes

**Comment by ala-n** [comment]
By 'grouping' I meant
- using specific selectors, 
so for example if we styling title just for filter so selector should be:
`.filter .title` 
We reduce potential conflicts in styles by doing this.
- Yeap, sorting is also good

> how to group it without copying some properties
That's not exactly the same thing, but let's see on example:
we have a lot of titles and we can have something like that 
`.title { font-family: SomeNiceTitleFont; font-size: 20px; color: black; margin: 0 5px; }`
(for all titles across the page)
and then if we need additional options in filter area so we can do:
`.filter .title { margin-bottom: 10px; color: gray; }`

--- 
Another problems left:
[-] (minor) html lang attribute missed
[-] form is grouping tag, instead of wrapping each filter input into form wrap whole filter area.

Generally looks much better.
Current score is **8+**.

**Comment by nikitadziadovich** [comment]
![](https://i.imgur.com/xk5JGCO.png)
you meant this by 'html lang attribute', right?

**Comment by ala-n** [comment]
Yeap, but global one (`<html lang="en">`) will be enough.
See https://www.w3.org/International/questions/qa-html-language-declarations for deep details.

**Comment by nikitadziadovich** [comment]
i've corrected mistakes
