### ISSUE TITLE
Task #4 (JS)

### ISSUE THREAD

**Issue by ala-n** [nikitadziadovich/Exadel#4]
[-] Better to add semicolon where it's needed and remove where it's redundant
```
 if (!skip) {
            skip = 0;
        };
```
[-] function expression without var operator will add function to the global scope, and failed in strict mode. Do not skip var operator.
[-] Prefer strict comparation (!== , ===)

[=] (clean code) Do not start function and variable names from capital letter until it is not a Module/Constructor/Class. 
 
[-] `delete photoPosts[index];` delete the key but not affect array length for example
Use Array.prototype.splice method.

[-] Remove console logs from methods bodies (in the final version)
leave only test result console logs

6 for now. (NOTE: correct 5th lab affect 4th mark, that mean if you will have 10 for 5th lab than you will have 10 for 4th automatically)

**Comment by nikitadziadovich** [comment]
hi!
i've started correct mistakes in scripts
i want to remove console logs from methods bodies using exit codes
so i use the following construction:
`switch (deletePhotoPost(id)) {
            case 0:
                console.log("successfully deleted");
                break;
            case -1:
                console.log("post with id " + id + " not found");
                break;
        }`
so now i'am wondering about how can i replace `deletePhotoPost(id)` with universal delegate or smth else
i tried to find smth about delegates in JS, but found nothing

**Comment by nikitadziadovich** [comment]
i've just uploaded task #5
